### ISSUE TITLE
data distribution image driver

### ISSUE THREAD

**Issue by kfox1111** [kubernetes-csi/drivers#85]
I (and others) would like to contribute a csi driver that is vendor agnostic and services the greater community.

I'm asking for a kubernetes-csi/image-driver repo be created to house this.

The idea would be to use an oci container image as a volume source. So that all the container caching/distribution mechanisms could be used to ship data.

One example use case:
Currently, I'm creating containers that contain some data to share out, and an nginx server so that the container can be launched and share out data. The problem is, it couples the update cycle of the nginx server and the data together. If the data is architecture specific (rpms for example), then you may need multiple combinations of builds depending on what architecture the container is expected to run on. For example, x86_64 rpms with an arm64 nginx so that an arm box can be used to bootstrap x86 boxes.

So, what I would like to do is be able to create pure data containers. IE a Dockerfile like:
FROM scratch
ADD /pile-of-rpms /rpms

And consume it in a pod such as:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.13-alpine
    ports:
    - containerPort: 80
    volumeMount:
    - name: data
      mountPath: /usr/share/nginx/html
  volumes:
  - name: data
    csi:
      driver: drivers.k8s.io/image-driver
      volumeAttributes:
          image: kfox1111/misc:test
```
